CREATE PROCEDURE [dbo].[Album_DeleteById] (
	@Id UNIQUEIDENTIFIER
)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	DELETE FROM [dbo].[Album]
	WHERE [Id] = @Id

	DELETE FROM [dbo].[AlbumTrack]
	WHERE [AlbumId] = @Id
END