CREATE PROCEDURE [dbo].[AudioTrack_DeleteById] (
	@Id UNIQUEIDENTIFIER
)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	DELETE FROM [dbo].[AudioTrack]
	WHERE [Id] = @Id
END