CREATE PROCEDURE [dbo].[Library_GetByUserId] (
	@UserId UNIQUEIDENTIFIER
)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT
		[Id],
		[UserId],
		[Name]
	FROM
		[dbo].[Library]
	WHERE
		[UserId] = @UserId
END