export const data = [
    { id: 1, name: "The (International) Noise Conspiracy"},
    { id: 2, name: "88 Fingers Louie"},
    { id: 3, name: "A New Found Glory"},
    { id: 4, name: "AFI"},
    { id: 5, name: "Against All Authority"},
    { id: 6, name: "Against Me!"},
    { id: 7, name: "Alkaline Trio"},
    { id: 8, name: "Anti-Flag"},
    { id: 9, name: "Anti-Heroes"},
    { id: 10, name: "As I Lay Dying"},
    { id: 11, name: "At the Drive-In"},
    { id: 12, name: "Avail"},
    { id: 13, name: "AWOLNATION"},
    { id: 14, name: "Bad Religion"},
    { id: 15, name: "Bayside"},
    { id: 16, name: "Blind Melon"},
    { id: 17, name: "Blink-182"},
    { id: 18, name: "Bob Marley & The Wailers"},
    { id: 19, name: "Botch"},
    { id: 20, name: "Cake"},
    { id: 21, name: "Daughters"},
    { id: 22, name: "Dead Kennedys"},
    { id: 23, name: "Death by Stereo"},
    { id: 24, name: "Deftones"},
    { id: 25, name: "DEVO"},
    { id: 26, name: "The Dillinger Escape Plan"},
    { id: 27, name: "Dog Fashion Disco"},
    { id: 28, name: "Dream Theater"},
    { id: 29, name: "Every Time I Die"},
    { id: 30, name: "The Fratellis"}
];